---
- name: Создание пользователя node-exporter
  ansible.builtin.user:
    name: "{{ node_exporter_user }}"
    shell: /sbin/nologin
    create_home: false
    system: true
  when: node_exporter_user is defined

- name: Создание директории /opt/node_exporter
  ansible.builtin.file:
    path: "{{ node_exporter_dir }}"
    state: directory
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_user }}"
    mode: '0755'

- name: Распаковка Node Exporter
  ansible.builtin.unarchive:
    src: >-
      {{ 'https://github.com/prometheus/node_exporter/releases/download/v' +
         node_exporter_version +
         '/node_exporter-' + node_exporter_version + '.linux-amd64.tar.gz' }}
    dest: "{{ node_exporter_dir }}"
    remote_src: true
    extra_opts: [--strip-components=1]
    creates: "{{ node_exporter_dir}}/node_exporter"
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_user }}"
    mode: '0755'
  when: node_exporter_user is defined

- name: Копирование systemd-юнита из шаблона
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: '0644'
  notify: Перезагрузка node-exporter

- name: Запуск и включение Node Exporter
  ansible.builtin.service:
    name: node_exporter
    state: started
    enabled: true

- name: Проверка, что node_exporter слушает порт 9100
  ansible.builtin.shell: ss -tuln | grep ':9100'
  register: port_check
  ignore_errors: true
  changed_when: false
  # Выполняется на управляющей машине, но проверяет состояние целевой

- name: Убедиться, что node_exporter слушает порт 9100
  ansible.builtin.assert:
    that:
      - port_check.rc == 0
    fail_msg: "Ошибка: node_exporter не слушает порт 9100!"
    success_msg: "OK: node_exporter слушает порт 9100"

- name: Проверка ответа node_exporter через HTTP
  ansible.builtin.uri:
    url: http://localhost:9100/metrics
    timeout: 10
  register: node_exporter_http_check
  ignore_errors: true
  delegate_to: "{{ inventory_hostname }}"

- name: Проверка статуса сервиса node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: started
    enabled: true
  changed_when: false
  register: node_exporter_service_status

- name: Убедиться, что сервис node_exporter активен
  ansible.builtin.assert:
    that:
      - node_exporter_service_status.status.ActiveState == "active"
      - node_exporter_service_status.status.SubState == "running"
    fail_msg: "Ошибка: Сервис node_exporter не активен! (ActiveState: {{ node_exporter_service_status.status.ActiveState }}, SubState: {{ node_exporter_service_status.status.SubState }})"
    success_msg: "OK: Сервис node_exporter активен и работает"
