---
- name: Установка зависимостей
  ansible.builtin.apt:
    name:
      - wget
      - gnupg
      - systemd
    state: present
    update_cache: true

- name: Создание группы (если не создана)
  ansible.builtin.group:
    name: "{{ alertmanager_user }}"
    state: present

- name: Создание пользователя alertmanager
  ansible.builtin.user:
    name: "{{ alertmanager_user }}"
    shell: /sbin/nologin
    create_home: false
    system: true

- name: Создание директории для Alertmanager
  ansible.builtin.file:
    path: "{{ alertmanager_dir }}"
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_user }}"
    state: directory
    mode: '0644'

- name: Распаковка и установка Alertmanager
  ansible.builtin.unarchive:
    src: >-
      {{ 'https://github.com/prometheus/alertmanager/releases/download/v' +
         alertmanager_version +
         '/alertmanager-' + alertmanager_version + '.linux-amd64.tar.gz' }}
    dest: "{{ alertmanager_dir }}"
    remote_src: true
    extra_opts: [--strip-components=1]
    creates: "{{ alertmanager_dir }}/alertmanager"
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_user }}"
    mode: '0755'

- name: Копирование конфигурации alertmanager.yml
  ansible.builtin.template:
    src: alertmanager.yml.j2
    dest: "{{ alertmanager_dir }}/alertmanager.yml"
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_user }}"
    mode: '0644'
  notify: Перезагрузка alertmanager

- name: Копирование systemd-юнита из шаблона
  ansible.builtin.template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
    mode: '0644'
  notify: Перезагрузка alertmanager

- name: Запуск и включение Alertmanager
  ansible.builtin.service:
    name: alertmanager
    state: started
    enabled: true
