---
- name: Установка зависимостей
  ansible.builtin.apt:
    name:
      - wget
      - gnupg
      - systemd
    state: present
    update_cache: true

- name: Создание пользователя prometheus
  ansible.builtin.user:
    name: "{{ prometheus_user }}"
    shell: /sbin/nologin
    system: true
    create_home: false

- name: Создание директории /opt/prometheus-server
  ansible.builtin.file:
    path: "{{ prometheus_dir }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: '0755'

- name: Распаковка Prometheus в /opt/prometheus-server
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "{{ prometheus_dir }}"
    remote_src: true
    extra_opts: [--strip-components=1]
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: '0755'
  args:
    creates: "{{ prometheus_dir }}/prometheus"

- name: Создание директории для данных
  ansible.builtin.file:
    path: "{{ prometheus_dir }}/data"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: '0755'

- name: Копирование конфигурации prometheus.yml
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_dir }}/prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: '0644'
  notify:
    - Перезагрузка systemd
    - Перезапуск Prometheus

- name: Копирование systemd-юнита
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    mode: '0644'
  notify:
    - Перезагрузка systemd
    - Перезапуск Prometheus

- name: Запуск и включение Prometheus
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: true
